second and third section completed
eerapheal/Ekpenisi-portfolio pull request #2
Opened 2022-08-19 05:56 UTC by eerapheal

finished mobile version of Ekepnisi portfolio.

2022-08-19 07:26 UTC, CollinsTatang requested changes
Hi @eerapheal, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:26 UTC, CollinsTatang commented on index.html
> +  </h3>
### **Great implementation of the project requirements**

- [ ] Please your design misses the horizontal line under the Recent Work title and your font doesn't match the [figmal design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) font.
### **Take Look at Figmal Design**
![figmalRecentWork](https://user-images.githubusercontent.com/55596970/185563824-b0f3ceba-f8d0-4c08-b1b6-c6ac6484c2ec.png)
### **Your Design**
![yourfont](https://user-images.githubusercontent.com/55596970/185563998-37e6fbc9-5878-481e-ba08-5406bff3537f.png)

2022-08-19 07:26 UTC, CollinsTatang commented on index.html
> +    <button class="btn-top" type="button">See projests</button>
- [ ] Please fix your see project button and Multi-Post font to match the [figmal design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27)

### **Figmal design**
![seeProButt](https://user-images.githubusercontent.com/55596970/185565442-75891acb-3698-47a5-b55d-da7511796564.png)
### **Your Design**
![client](https://user-images.githubusercontent.com/55596970/185565681-142bf876-f7c1-4918-a14e-82260bcc3ebc.png)

2022-08-20 03:22 UTC, franclobo requested changes
Hi @eerapheal , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

Consider this suggestions:

- [ ] We must follow the [READMe template](https://github.com/microverseinc/readme-template/blob/master/README.md) to have a professional file. 💯 
- [ ] We could add a descriptive title on Pull Request. 😎 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 03:22 UTC, franclobo commented on index.html
> +      </div>
- [ ] **[OPTIONAL]** There are three ✌🏽 more cards than in the Figma template, please delete them to stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

![image](https://user-images.githubusercontent.com/58642949/185726743-002946c7-8f48-450e-b72a-74ef917a5bb5.png)

2022-08-20 12:56 UTC, ElsonOtake approved these changes
# status: APPROVED :green_circle: :100: 

Hi @eerapheal, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

![Minions](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Optional suggestions

- [OPTIONAL] Please check the suggested changes in your code for improvements.
- [OPTIONAL] Please create a more professional Pull Request following the [Document your repo in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md).

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 👍 👍 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 12:56 UTC, ElsonOtake commented on style.css
> +  width: 375px;
- [OPTIONAL] Please avoid the use of a limited width size. Don't declare width or use a width of 100% and control the size using margins or paddings. It creates a more responsible page, a better user experience, and works in any kind of display. As not required by the previous reviewers, I consider that optional.
Check how your app could be in this case:

Current app
<img width="822" alt="Screen Shot 2022-08-20 at 9 32 44 AM" src="https://user-images.githubusercontent.com/47673311/185746365-4c890244-6c1d-4077-a3ea-8426dd541c71.png">

Without width limitation:
<img width="822" alt="Screen Shot 2022-08-20 at 9 21 57 AM" src="https://user-images.githubusercontent.com/47673311/185746395-28741731-8af8-4a54-8325-bd7a6fda65d1.png">
<img width="822" alt="Screen Shot 2022-08-20 at 9 22 16 AM" src="https://user-images.githubusercontent.com/47673311/185746398-142315a1-5f35-41b7-ab92-73e08806ed7a.png">

2022-08-20 12:56 UTC, ElsonOtake commented on style.css
> +}
- [OPTIONAL] Please create a border for the button when hovering following the Figma template. Check the other buttons for the same issue. As not requested by the previous reviewers, I consider that optional.

2022-08-20 12:56 UTC, ElsonOtake commented on style.css
> +  font-family: 'Inter', serif;
- [OPTIONAL] Please set up the font following the [Google fonts](https://fonts.google.com/) instruction using `<link>` or `@import`. Example: 
```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
```
As not requested by the previous reviewer. I consider that optional. Check other fonts for the same issue.

2022-08-23 13:21 UTC, eerapheal commented
thanks for the review

2022-08-23 13:22 UTC, merged